export const ACTION_TYPES = {
  GET_CARDS_START: 'GET_CARDS_START',
  GET_CARDS_SUCCESS: 'GET_CARDS_SUCCESS',
  GET_CARDS_FAILURE: 'GET_CARDS_FAILURE',
  POST_CARD_START: 'POST_CARD_START',
  POST_CARD_SUCCESS: 'POST_CARD_SUCCESS',
  POST_CARD_FAILURE: 'POST_CARD_FAILURE',
  DELETE_CARD_START: 'DELETE_CARD_START',
  DELETE_CARD_SUCCESS: 'DELETE_CARD_SUCCESS',
  DELETE_CARD_FAILURE: 'DELETE_CARD_FAILURE',
  PUT_CARD_START: 'PUT_CARD-START',
  PUT_CARD_SUCCESS: 'PUT_CARD-SUCCESS',
  PUT_CARD_FAILURE: 'PUT_CARD-FAILURE',
};
