export const ACTION_TYPES = {
  GET_CARDS_SUCCESS: 'GET_CARDS_SUCCESS',
  POST_CARD_SUCCESS: 'POST_CARD_SUCCESS',
  DELETE_CARD_SUCCESS: 'DELETE_CARD_SUCCESS',
  PUT_CARD_SUCCESS: 'PUT_CARD-SUCCESS',
  CARD_FAILURE: 'CARD-FAILURE',
};
